### PR TITLE
#8 Fix for NPE on constructor factory 

### LINKED ISSUE #8: NPE when Factory is defined as test class constructor
GIven test class
```
public class ConstructorFactory {

    public ConstructorFactory(){}

    @DataProvider
    public Object[] ints(){return new Object[]{1, 2, 3};}

    @Factory(dataProvider = "ints")
    public ConstructorFactory(int i){ }

    @Test
    public void test(){}
}
```
Running this test class with testng with ListenerChain applied will cause NPE
```
        ListenerChain lc = new ListenerChain();
        TestListenerAdapter tla = new TestListenerAdapter();

        TestNG testNG = new TestNG();
        testNG.setTestClasses(new Class[]{ConstructorFactory.class});
        testNG.addListener((ITestNGListener) lc);
        testNG.addListener((ITestNGListener) tla);
        testNG.run();
```

This is because Method method reference which is passed to transform() is null and in this case IFactoryAnnotation annotation reference is not null.  

Partial stacktrace: 
```
java.lang.NullPointerException
	at com.nordstrom.automation.testng.ListenerChain.attachListeners(ListenerChain.java:593)
	at com.nordstrom.automation.testng.ListenerChain.transform(ListenerChain.java:146)
	at org.testng.internal.annotations.JDK15AnnotationFinder.transform(JDK15AnnotationFinder.java:180)
	at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:231)
	at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:216)
	at org.testng.internal.ClassHelper.findDeclaredFactoryMethods(ClassHelper.java:146)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:133)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:40)
	at org.testng.TestRunner.initMethods(TestRunner.java:403)
	at org.testng.TestRunner.init(TestRunner.java:252)
	at org.testng.TestRunner.init(TestRunner.java:222)
	at org.testng.TestRunner.<init>(TestRunner.java:163)
```

### PR DESCRIPTION
**Pull request by yaroslav-orel**
Fixes #8 
  
However bacause at this point testng doesn't inject dataProviderClass property implicitly into IFactoryAnnotation annotation reference client needs to explicitly claim dataProivderClass inside @Factory annotation (even if data provider and factory are in the same class) like this: 
```
@Factory(dataProvider = "ints", dataProviderClass = ConstructorFactory.class)
```
For details please refer to this issue: https://github.com/cbeust/testng/issues/1631

### CODE REVIEW

File: src/main/java/com/nordstrom/automation/testng/ListenerChain.java [hunk 1]
```diff
@@ -171,7 +142,10 @@ public void transform(IDataProviderAnnotation annotation, Method method) {
      */
     @Override
     public void transform(IFactoryAnnotation annotation, Method method) {
```
Comment (sbabcoc) [inline src/main/java/com/nordstrom/automation/testng/ListenerChain.java]: Is it possible for this issue to affect the other two `transform` methods?

Comment (yaroslav-orel) [reply src/main/java/com/nordstrom/automation/testng/ListenerChain.java]: Hard to tell. I targeted only this overload of transform(). Maybe we need to add several more tests

Comment (sbabcoc) [reply src/main/java/com/nordstrom/automation/testng/ListenerChain.java]: I think you're OK, because this is the only method that specifically handles transforming IFactoryAnnotation.
